title:  North End Makerspace Makerspace Policies (Draft)
description: ""

# theme: minima
remote_theme: jekyll/minima # gh-pages bundled `minima` doesn't support dark mode
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  hide_site_feed_link: true

